On Error Resume Next
Const adOpenStatic = 3
Const adLockOptimistic = 3
Dim oArg, comOption
Set comOption = 0Set oArg = WScript.ArgumentsSelect Case oArg(0)   Case "makefiles"      comOption = 1   Case "addusers"      comOption = 2End Select
if (comOption = 0) Then   Wscript.echo "  Usage is:"   Wscript.echo "  cscript bulkload_ad.vbs makefiles|addusers" & vbCrLf   Wscript.quitEnd If
Set conn = CreateObject("ADODB.Connection")Set rs   = CreateObject("ADODB.Recordset")
Set fs = CreateObject("Scripting.FileSystemObject")Set FileAD   = fs.CreateTextFile("ad_" & Year(now) & Month(now) & Day(now) & ".txt", True)Set File800  = fs.CreateTextFile("fusion_" & Year(now) & Month(now) & Day(now) & "_800.txt", True)Set FileNORC = fs.CreateTextFile("fusion_" & Year(now) & Month(now) & Day(now) & "_norc.txt", True)Set FilePO  = fs.CreateTextFile("fusion_" & Year(now) & Month(now) & Day(now) & "_po.txt", True)Set FileNY  = fs.CreateTextFile("fusion_" & Year(now) & Month(now) & Day(now) & "_ny.txt", True)Set FileLoc  = fs.CreateTextFile("fusion_" & Year(now) & Month(now) & Day(now) & "_loc.txt", True)
conn.Open "Provider= Microsoft.ACE.OLEDB.12.0; Data Source=\\norc.org\projects\tsso\TSSO_Databases\TSSO New Network Users.accdb"rs.Open   "SELECT [Last Name],[First Name], [ID Number], [Admin Manager], " & _          "Department, Location FROM [Fusion_Network Account List]" & _          " where [AD Account Flag] <> 'Y' ", conn, adOpenStatic, adLockOptimisticrs.MoveFirst
Do Until rs.EOF   sManager        = rs.Fields.Item("Admin Manager")   if (sManager = "Locating Account") Then      sDisplayName = "loc-" & LCase(rs.Fields.Item("Last Name") & "-" & Left(rs.Fields.Item("First Name"),1) )      sFileType    = "loc"   elseif (sManager = "800 Call_in_account") Then      sDisplayName = "800-" & LCase(rs.Fields.Item("Last Name") & "-" & Left(rs.Fields.Item("First Name"),1) )      sFileType    = "800"   else      sDisplayName = LCase(rs.Fields.Item("Last Name") & "-" & rs.Fields.Item("First Name"))      sFileType    = ""   end if   sSamAccountName = rs.Fields.Item("ID Number")   suserPrincipalName = sDisplayName   sSn             = rs.Fields.Item("Last Name")   sgivenName      = rs.Fields.Item("First Name")   strName         = LCase(rs.Fields.Item("First Name"))   If (Len(strName) < 8) Then      sPassword    = "Interview1!"   End If   semployeeNumber     = rs.Fields.Item("ID Number")   sCompany        = rs.Fields.Item("Department")   if (sCompany = "Precision Opinion") Then      if (sFileType = "") Then         sFileType  = "PO"      End If   Elseif (sCompany = "Universal Survey") Then      if (sFileType = "") Then         sFileType  = "ABQ"      End If   Elseif (sCompany = "Wichita") Then      if (sFileType = "") Then         sFileType  = "WCT"      End If   Elseif (sCompany = "NORC") Then      if (sFileType = "") Then         sFileType  = "NORC"      End If   End If         sSt              = rs.Fields.Item("Location")      Select Case sSt      Case "55E"           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=interviewer,ou=dt,ou=callcenter,ou=users,ou=prod,DC=norc,dc=org"      case "ABQ"           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=interviewer,ou=ab,ou=callcenter,ou=users,ou=prod,DC=norc,dc=org"      Case "Las Vegas"           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=interviewer,ou=lv,ou=callcenter,ou=users,ou=prod,DC=norc,dc=org"      Case "DCATI"           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=interviewer,ou=1n,ou=callcenter,ou=users,ou=prod,DC=norc,dc=org"      Case "WCT"           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=interviewer,ou=wi,ou=callcenter,ou=users,ou=prod,DC=norc,dc=org"        Case Else           sOU = "LDAP://S12ZAPAD02047.norc.org/ou=newusers,ou=staging,ou=prod,DC=norc,dc=org"     
   End Select
   Select Case comOption      Case "1"         FileAD.WriteLine(sDisplayName & "|" & sSn & "|" & sGivenName & "||" & sPassword & "|" & semployeeNumber & "|" & sManager & "|" & sCompany & "|" & sSt)  Select Case sFileType     Case "800"        File800.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)     Case "NORC"        FileNORC.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)     Case "PO"        FilePO.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)     Case "ABQ"        FilePO.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)      Case "WCT"        Fileloc.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)     Case "loc"        Fileloc.WriteLine(sDisplayName & "|" & sSn & "," & sGivenName & "|" & sCompany & "|" & semployeeNumber)
         End Select      Case "2"         CreateaUser sOU   End Select
   rs.MoveNextLooprs.Close
Set oTF    = NothingSet oFSO   = NothingSet oUser  = NothingSet oGroup = NothingSet oOU    = Nothing
'------------------------------------------------------------------------------' Create a User account'------------------------------------------------------------------------------Sub CreateaUser(sOU)
   Set oOU   = GetObject(sOU)   Set oUser = oOU.Create("user", "cn=" & sdisplayName)   Set oGroup = GetObject ("LDAP://CN=Bv7Users,OU=Security,OU=Groups,OU=Prod,DC=norc,DC=org")    oUser.put "samAccountName"    , sDisplayName   oUser.put "DisplayName"       , sDisplayName   oUser.put "employeeNumber"        , semployeeNumber   oUser.put "givenName"         , sgivenName   oUser.put "sn"                , sSn   oUser.put "company"           , sCompany   oUser.put "st"                , sSt   oUser.put "CN"                , sdisplayName   oUser.put "userPrincipalName" , semployeeNumber & "@norc.org"
   'SAVE the INFO and Move ON   oUser.SetInfo   oGroup.SetInfo   Wscript.Echo "created user " & ouser.Name
   oUser.SetPassword  sPassword   oUser.AccountDisabled = False   oUser.SetInfo
'   Set oGroup = GetObject ("LDAP://CN=Bv7Users,OU=Security,OU=Groups,OU=Prod,DC=norc,DC=org") '   Set objUser = GetObject(sdisplayname)'   objGroup.Add (oUser)'   oGroup.SetInfo
   Set oUSer = Nothing
End Sub
'------------------------------------------------------------------------------'Add a user to Fusion environment'------------------------------------------------------------------------------Function AddUser( strUserName, strUserFull, strUserDesc, stremployeeNumber)
  Dim strUser, userID, Options
  Set strUser = pool.Insert()  strUser.PutProperty 2,   Options, strUserName  strUser.PutProperty 3,   Options, strUserFull  strUser.PutProperty 4,   Options, strUserDesc  strUser.PutProperty 14,  Options, srcUserID.GetProperty(14, Options )  strUser.PutProperty 536, Options, srcUserID.GetProperty(536, Options )  strUser.PutProperty 543, Options, stremployeeNumber
  userID = strUser.Update()  if Err <> 0 Then    WriteLogMessage "Error. " & Err.description  Else    WriteLogMessage "User "& strUserName & " (" & CLng(userID) & ") added."    Wscript.echo "User "& strUserName & " (" & CLng(userID) & ") added."  End if
  Set userID  = Nothing  Set strUser = Nothing
End Function
'------------------------------------------------------------------------------' Function for writing a message to Fusion Log'------------------------------------------------------------------------------Function WriteLogMessage( text )   Dim message
   Set message = CreateObject( "LogSrv.Message", strServerName )
   message.Type = CByte( MSGTYPE_INFORMATION )   message.Body = text   message.ModuleName = "PT.AddUser"   message.Write
   Set message = Nothing
End Function
